CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT uk_usuarios_email UNIQUE (email),

    CONSTRAINT ck_usuarios_perfil
        CHECK (perfil IN ('ADMIN', 'RECEPCIONISTA', 'MEDICO'))
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expira_em TIMESTAMP WITH TIME ZONE NOT NULL,
    revogado_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_origem VARCHAR(45),
    user_agent VARCHAR(500),

    CONSTRAINT fk_refresh_tokens_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_refresh_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_refresh_tokens_expiracao
        CHECK (expira_em > criado_em)
);

CREATE INDEX idx_usuarios_email
    ON usuarios (email);

CREATE INDEX idx_usuarios_perfil
    ON usuarios (perfil);

CREATE INDEX idx_usuarios_ativo
    ON usuarios (ativo);

CREATE INDEX idx_refresh_tokens_usuario
    ON refresh_tokens (usuario_id);

CREATE INDEX idx_refresh_tokens_expira_em
    ON refresh_tokens (expira_em);