CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_completo VARCHAR(180) NOT NULL,
    cpf CHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    sexo VARCHAR(30),
    telefone VARCHAR(20) NOT NULL,
    telefone_secundario VARCHAR(20),
    email VARCHAR(180),
    nome_mae VARCHAR(180),
    cep CHAR(8),
    logradouro VARCHAR(180),
    numero VARCHAR(20),
    complemento VARCHAR(100),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado CHAR(2),
    observacoes TEXT,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT uk_pacientes_cpf
        UNIQUE (cpf),

    CONSTRAINT ck_pacientes_cpf
        CHECK (cpf ~ '^[0-9]{11}$'),

    CONSTRAINT ck_pacientes_cep
        CHECK (cep IS NULL OR cep ~ '^[0-9]{8}$'),

    CONSTRAINT ck_pacientes_estado
        CHECK (estado IS NULL OR estado ~ '^[A-Z]{2}$'),

    CONSTRAINT ck_pacientes_data_nascimento
        CHECK (data_nascimento <= CURRENT_DATE)
);

CREATE INDEX idx_pacientes_nome
    ON pacientes (nome_completo);

CREATE INDEX idx_pacientes_cpf
    ON pacientes (cpf);

CREATE INDEX idx_pacientes_telefone
    ON pacientes (telefone);

CREATE INDEX idx_pacientes_ativo
    ON pacientes (ativo);