CREATE TABLE medicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome_completo VARCHAR(180) NOT NULL,
    crm_numero VARCHAR(20) NOT NULL,
    crm_uf CHAR(2) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(180),
    duracao_consulta_minutos SMALLINT NOT NULL DEFAULT 30,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT fk_medicos_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_medicos_usuario
        UNIQUE (usuario_id),

    CONSTRAINT uk_medicos_crm
        UNIQUE (crm_numero, crm_uf),

    CONSTRAINT ck_medicos_crm_uf
        CHECK (crm_uf ~ '^[A-Z]{2}$'),

    CONSTRAINT ck_medicos_duracao
        CHECK (duracao_consulta_minutos > 0)
);

CREATE TABLE especialidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT uk_especialidades_nome
        UNIQUE (nome)
);

CREATE TABLE medicos_especialidades (
    medico_id BIGINT NOT NULL,
    especialidade_id BIGINT NOT NULL,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_medicos_especialidades
        PRIMARY KEY (medico_id, especialidade_id),

    CONSTRAINT fk_medicos_especialidades_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_medicos_especialidades_especialidade
        FOREIGN KEY (especialidade_id)
        REFERENCES especialidades (id)
        ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uk_medicos_especialidade_principal
    ON medicos_especialidades (medico_id)
    WHERE principal = TRUE;

CREATE INDEX idx_medicos_nome
    ON medicos (nome_completo);

CREATE INDEX idx_medicos_crm
    ON medicos (crm_numero, crm_uf);

CREATE INDEX idx_medicos_ativo
    ON medicos (ativo);

CREATE INDEX idx_especialidades_nome
    ON especialidades (nome);

CREATE INDEX idx_especialidades_ativo
    ON especialidades (ativo);