CREATE TABLE agendas_medicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    dia_semana SMALLINT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    intervalo_inicio TIME,
    intervalo_fim TIME,
    duracao_consulta_minutos SMALLINT NOT NULL,
    vigencia_inicio DATE NOT NULL,
    vigencia_fim DATE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT fk_agendas_medicas_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_agendas_medicas_dia
        CHECK (dia_semana BETWEEN 1 AND 7),

    CONSTRAINT ck_agendas_medicas_horario
        CHECK (hora_inicio < hora_fim),

    CONSTRAINT ck_agendas_medicas_duracao
        CHECK (duracao_consulta_minutos > 0),

    CONSTRAINT ck_agendas_medicas_vigencia
        CHECK (
            vigencia_fim IS NULL
            OR vigencia_fim >= vigencia_inicio
        ),

    CONSTRAINT ck_agendas_medicas_intervalo
        CHECK (
            (
                intervalo_inicio IS NULL
                AND intervalo_fim IS NULL
            )
            OR
            (
                intervalo_inicio IS NOT NULL
                AND intervalo_fim IS NOT NULL
                AND intervalo_inicio < intervalo_fim
                AND intervalo_inicio >= hora_inicio
                AND intervalo_fim <= hora_fim
            )
        )
);

CREATE TABLE bloqueios_agenda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medico_id BIGINT NOT NULL,
    inicio_em TIMESTAMP WITH TIME ZONE NOT NULL,
    fim_em TIMESTAMP WITH TIME ZONE NOT NULL,
    motivo VARCHAR(300) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    cancelado_em TIMESTAMP WITH TIME ZONE,
    cancelado_por BIGINT,

    CONSTRAINT fk_bloqueios_agenda_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_bloqueios_agenda_periodo
        CHECK (inicio_em < fim_em),

    CONSTRAINT ck_bloqueios_agenda_tipo
        CHECK (
            tipo IN (
                'FERIAS',
                'AUSENCIA',
                'REUNIAO',
                'FERIADO',
                'ADMINISTRATIVO',
                'OUTRO'
            )
        )
);

CREATE TABLE agendamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    especialidade_id BIGINT NOT NULL,
    inicio_em TIMESTAMP WITH TIME ZONE NOT NULL,
    fim_em TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    tipo_atendimento VARCHAR(30) NOT NULL DEFAULT 'PRESENCIAL',
    motivo_consulta VARCHAR(500),
    observacoes VARCHAR(1000),
    confirmado_em TIMESTAMP WITH TIME ZONE,
    presenca_em TIMESTAMP WITH TIME ZONE,
    cancelado_em TIMESTAMP WITH TIME ZONE,
    motivo_cancelamento VARCHAR(500),
    agendamento_origem_id BIGINT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT fk_agendamentos_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_agendamentos_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_agendamentos_especialidade
        FOREIGN KEY (especialidade_id)
        REFERENCES especialidades (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_agendamentos_origem
        FOREIGN KEY (agendamento_origem_id)
        REFERENCES agendamentos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_agendamentos_periodo
        CHECK (inicio_em < fim_em),

    CONSTRAINT ck_agendamentos_status
        CHECK (
            status IN (
                'AGENDADO',
                'CONFIRMADO',
                'PACIENTE_PRESENTE',
                'EM_ATENDIMENTO',
                'CONCLUIDO',
                'CANCELADO',
                'NAO_COMPARECEU'
            )
        ),

    CONSTRAINT ck_agendamentos_tipo
        CHECK (
            tipo_atendimento IN (
                'PRESENCIAL',
                'TELEMEDICINA',
                'RETORNO'
            )
        )
);

CREATE TABLE historicos_agendamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id BIGINT NOT NULL,
    status_anterior VARCHAR(30),
    status_novo VARCHAR(30) NOT NULL,
    inicio_anterior_em TIMESTAMP WITH TIME ZONE,
    fim_anterior_em TIMESTAMP WITH TIME ZONE,
    inicio_novo_em TIMESTAMP WITH TIME ZONE,
    fim_novo_em TIMESTAMP WITH TIME ZONE,
    motivo VARCHAR(500),
    alterado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alterado_por BIGINT,

    CONSTRAINT fk_historicos_agendamento
        FOREIGN KEY (agendamento_id)
        REFERENCES agendamentos (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_agendas_medicas_medico
    ON agendas_medicas (medico_id, dia_semana);

CREATE INDEX idx_bloqueios_agenda_medico_periodo
    ON bloqueios_agenda (medico_id, inicio_em, fim_em);

CREATE INDEX idx_agendamentos_medico_inicio
    ON agendamentos (medico_id, inicio_em);

CREATE INDEX idx_agendamentos_paciente_inicio
    ON agendamentos (paciente_id, inicio_em);

CREATE INDEX idx_agendamentos_status
    ON agendamentos (status);

CREATE INDEX idx_agendamentos_inicio
    ON agendamentos (inicio_em);

CREATE INDEX idx_historicos_agendamento
    ON historicos_agendamento (agendamento_id, alterado_em);