CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agendamento_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    iniciada_em TIMESTAMP WITH TIME ZONE NOT NULL,
    finalizada_em TIMESTAMP WITH TIME ZONE,
    status VARCHAR(30) NOT NULL,
    queixa_principal TEXT,
    historia_doenca_atual TEXT,
    avaliacao TEXT,
    diagnostico TEXT,
    conduta TEXT,
    observacoes TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_consultas_agendamento
        FOREIGN KEY (agendamento_id)
        REFERENCES agendamentos (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_consultas_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_consultas_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_consultas_agendamento
        UNIQUE (agendamento_id),

    CONSTRAINT ck_consultas_status
        CHECK (
            status IN (
                'EM_ATENDIMENTO',
                'FINALIZADA',
                'CANCELADA'
            )
        ),

    CONSTRAINT ck_consultas_periodo
        CHECK (
            finalizada_em IS NULL
            OR finalizada_em >= iniciada_em
        )
);

CREATE TABLE prontuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    tipo_sanguineo VARCHAR(5),
    historico_familiar TEXT,
    doencas_preexistentes TEXT,
    medicamentos_em_uso TEXT,
    observacoes_gerais TEXT,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT,
    atualizado_em TIMESTAMP WITH TIME ZONE,
    atualizado_por BIGINT,

    CONSTRAINT fk_prontuarios_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_prontuarios_paciente
        UNIQUE (paciente_id)
);

CREATE TABLE alergias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prontuario_id BIGINT NOT NULL,
    substancia VARCHAR(180) NOT NULL,
    reacao VARCHAR(500),
    gravidade VARCHAR(20) NOT NULL DEFAULT 'NAO_INFORMADA',
    observacoes VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    registrado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    registrado_por BIGINT,

    CONSTRAINT fk_alergias_prontuario
        FOREIGN KEY (prontuario_id)
        REFERENCES prontuarios (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_alergias_gravidade
        CHECK (
            gravidade IN (
                'LEVE',
                'MODERADA',
                'GRAVE',
                'NAO_INFORMADA'
            )
        )
);

CREATE TABLE receitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    orientacoes_gerais TEXT,
    emitida_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    validade_ate DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'EMITIDA',
    cancelada_em TIMESTAMP WITH TIME ZONE,
    motivo_cancelamento VARCHAR(500),

    CONSTRAINT fk_receitas_consulta
        FOREIGN KEY (consulta_id)
        REFERENCES consultas (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receitas_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_receitas_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_receitas_status
        CHECK (status IN ('EMITIDA', 'CANCELADA'))
);

CREATE TABLE itens_receita (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receita_id BIGINT NOT NULL,
    medicamento VARCHAR(200) NOT NULL,
    dosagem VARCHAR(100) NOT NULL,
    via_administracao VARCHAR(100),
    frequencia VARCHAR(150) NOT NULL,
    duracao VARCHAR(100),
    quantidade VARCHAR(100),
    orientacoes VARCHAR(500),
    ordem SMALLINT NOT NULL,

    CONSTRAINT fk_itens_receita_receita
        FOREIGN KEY (receita_id)
        REFERENCES receitas (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_itens_receita_ordem
        CHECK (ordem > 0),

    CONSTRAINT uk_itens_receita_ordem
        UNIQUE (receita_id, ordem)
);

CREATE TABLE atestados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id BIGINT NOT NULL,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    quantidade_dias SMALLINT NOT NULL,
    texto TEXT NOT NULL,
    cid VARCHAR(20),
    autorizacao_cid BOOLEAN NOT NULL DEFAULT FALSE,
    emitido_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'EMITIDO',
    cancelado_em TIMESTAMP WITH TIME ZONE,
    motivo_cancelamento VARCHAR(500),

    CONSTRAINT fk_atestados_consulta
        FOREIGN KEY (consulta_id)
        REFERENCES consultas (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_atestados_paciente
        FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_atestados_medico
        FOREIGN KEY (medico_id)
        REFERENCES medicos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_atestados_dias
        CHECK (quantidade_dias > 0),

    CONSTRAINT ck_atestados_status
        CHECK (status IN ('EMITIDO', 'CANCELADO')),

    CONSTRAINT ck_atestados_cid
        CHECK (
            autorizacao_cid = TRUE
            OR cid IS NULL
        )
);

CREATE INDEX idx_consultas_paciente
    ON consultas (paciente_id, iniciada_em);

CREATE INDEX idx_consultas_medico
    ON consultas (medico_id, iniciada_em);

CREATE INDEX idx_alergias_prontuario
    ON alergias (prontuario_id, ativo);

CREATE INDEX idx_receitas_consulta
    ON receitas (consulta_id);

CREATE INDEX idx_atestados_consulta
    ON atestados (consulta_id);