CREATE TABLE auditorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    acao VARCHAR(100) NOT NULL,
    entidade VARCHAR(100),
    entidade_id BIGINT,
    descricao VARCHAR(1000),
    dados_anteriores JSONB,
    dados_novos JSONB,
    ip_origem VARCHAR(45),
    user_agent VARCHAR(500),
    ocorrido_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_auditorias_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_auditorias_usuario
    ON auditorias (usuario_id);

CREATE INDEX idx_auditorias_acao
    ON auditorias (acao);

CREATE INDEX idx_auditorias_entidade
    ON auditorias (entidade, entidade_id);

CREATE INDEX idx_auditorias_ocorrido_em
    ON auditorias (ocorrido_em);

CREATE INDEX idx_refresh_tokens_validos
    ON refresh_tokens (usuario_id, expira_em)
    WHERE revogado_em IS NULL;

CREATE INDEX idx_agendamentos_ativos_medico
    ON agendamentos (medico_id, inicio_em, fim_em)
    WHERE status IN (
        'AGENDADO',
        'CONFIRMADO',
        'PACIENTE_PRESENTE',
        'EM_ATENDIMENTO'
    );

CREATE INDEX idx_agendamentos_ativos_paciente
    ON agendamentos (paciente_id, inicio_em, fim_em)
    WHERE status IN (
        'AGENDADO',
        'CONFIRMADO',
        'PACIENTE_PRESENTE',
        'EM_ATENDIMENTO'
    );