spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/clinica_medica_test
    username: clinica_test
    password: clinica_test

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  docker:
    compose:
      enabled: false

logging:
  level:
    root: WARN
    br.com.galeradoti.clinica: INFO