spring:
  application:
    name: clinica-medica-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jackson:
    default-property-inclusion: non_null
    time-zone: America/Sao_Paulo

server:
  port: ${BACKEND_PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

info:
  application:
    name: Clínica Médica API
    description: API REST para gerenciamento de clínica médica
    version: 0.1.0
    
app:
  security:
    jwt:
      issuer: clinica-medica-api
      access-token-expiration-seconds: 900
      refresh-token-expiration-days: 7
      secret: ${JWT_SECRET_BASE64}

    cookie:
      secure: ${AUTH_COOKIE_SECURE:false}
      same-site: ${AUTH_COOKIE_SAME_SITE:Strict}